// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ1WzM3IWwVKHWceuEntmoybd1DMayDTE',
    appId: '1:684957584170:web:ea0e5947185b637de8ac53',
    messagingSenderId: '684957584170',
    projectId: 'digital-kabaria-app',
    authDomain: 'digital-kabaria-app.firebaseapp.com',
    storageBucket: 'digital-kabaria-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU2tglDwQVpgO2oGQGXen2_kQLXJmDLg4',
    appId: '1:684957584170:android:b4e597f96dc36d00e8ac53',
    messagingSenderId: '684957584170',
    projectId: 'digital-kabaria-app',
    storageBucket: 'digital-kabaria-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcQqXNgKtpe0uojKZF5VDWQyAC6IQiZ0A',
    appId: '1:684957584170:ios:7bdc8cea138158a8e8ac53',
    messagingSenderId: '684957584170',
    projectId: 'digital-kabaria-app',
    storageBucket: 'digital-kabaria-app.appspot.com',
    iosBundleId: 'com.example.digitalKabariaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcQqXNgKtpe0uojKZF5VDWQyAC6IQiZ0A',
    appId: '1:684957584170:ios:7bdc8cea138158a8e8ac53',
    messagingSenderId: '684957584170',
    projectId: 'digital-kabaria-app',
    storageBucket: 'digital-kabaria-app.appspot.com',
    iosBundleId: 'com.example.digitalKabariaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ1WzM3IWwVKHWceuEntmoybd1DMayDTE',
    appId: '1:684957584170:web:ceeb3780fc9266dae8ac53',
    messagingSenderId: '684957584170',
    projectId: 'digital-kabaria-app',
    authDomain: 'digital-kabaria-app.firebaseapp.com',
    storageBucket: 'digital-kabaria-app.appspot.com',
  );
}
