import 'package:get/get_navigation/src/root/internacionalization.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          "Digital Kabariya": "Digital Kabariya",
          "Welcome Back! Access your account":
              "Welcome Back! Access your account",
          "Welcome! Create your account": "Welcome! Create your account",
          "Email": "Email",
          "Password": "Password",
          "Enter Email": "Enter Email",
          "Enter Password": "Enter Password",
          "Reset Password?": "Reset Password?",
          "Login": "Login",
          "Create Account": "Create Account",
          "Welcome! Create your\naccount": "Welcome! Create your\naccount",
          "Full Name": "Full Name",
          "Email Address": "Email Address",
          "Phone No": "Phone No",
          "Sign Up As!": "Sign Up As!",
          "Set Password": "Set Password",
          "Confirm Password": "Confirm Password",
          "Create Account": "Create Account",
          "Already Registered?": "Already Registered?",
          "Pick Image": "Pick Image",
          "Product Name": "Product Name",
          "Product Description": "Product Description",
          "Phone Number": "Phone Number",
          "Second Phone Number": "Second Phone Number",
          "Product Price": "Product Price",
          "Pick Location": "Pick Location",
          "Record Voice": "Record Voice",
          "Update Profile": "Update Profile",
          "Send Feedback": "Send Feedback",
          "View Reply": "View Reply",
          "Log out": "Log out",
          "Submit": "Submit",
          "Mark as Sold": "Mark as Sold",
          "Delete": "Delete",
          "Post New": "Post New",
          "Sell": "Sell",
          "Rates": "Rates",
          "Profile": "Profile",
          'Select Scrap Type': 'Select Scrap Type',
          'Edit Profile': 'Edit Profile',
          'Edit and update your profile information':
              'Edit and update your profile information',
          'Send Feedback to admin': 'Send Feedback to admin',
          'Share your feedback with us': 'Share your feedback with us',
          'View admin Reply': 'View admin Reply',
          'Check replies to your feedback': 'Check replies to your feedback',
          'Logout': 'Logout',
          'Sign out of your account': 'Sign out of your account',
          "Second Phone Number (Optional)": "Second Phone Number (Optional)",
          "Home": "Home",
          "Profile": "Profile",
          "Bids": "Bids",
          "VIew All Bids": "VIew All Bids",
          "Post Bid": "Post Bid",
          "Plastic": "Plastic",
          "Approved": "Approved",
          "Pending": "Pending",
          "Send Bid": "Send Bid",
          'Metal': 'Metal',
          'Wood': 'Wood',
          'Paper': 'Paper',
          'Fabric': 'Fabric',
          'Machinery': 'Machinery',
          "Search": "Search",
          "Product Details": "Product Details",
          "Track Location": "Track Location",
          "Call Number One": "Call Number One",
          "Call Number Two": "Call Number Two",
          "Clear All": "Clear All",
          "Apply": "Apply",
          'Features:': 'Features:',
          "Select Filters": "Select Filters"
        },
        'ur': {
          "Digital Kabariya": "ڈیجیٹل کباریہ",
          "Welcome Back! Access your account":
              "خوش آمدید! اپنا اکاؤنٹ لاگ ان کریں۔",
          "Welcome! Create your account": "خوش آمدید! اپنا اکاؤنٹ بنائیں",
          "Email": "ای میل",
          "Password": "پاس ورڈ",
          "Enter Email": "ای میل درج کریں",
          "Enter Password": "پاس ورڈ درج کریں",
          "Reset Password?": "پاس ورڈ ری سیٹ کریں؟",
          "Login": "لاگ ان",
          "Create Account": "اکاؤنٹ بنائیں",
          "Welcome! Create your\naccount": "خوش آمدید! اپنا\nاکاؤنٹ بنائیں",
          "Full Name": "پورا نام",
          "Email Address": "ای میل ایڈریس",
          "Phone No": "فون نمبر",
          "Sign Up As!": "بطور سائن اپ کریں!",
          "Set Password": "پاس ورڈ سیٹ کریں",
          "Confirm Password": "پاس ورڈ کی تصدیق کریں",
          "Create Account": "اکاؤنٹ بنائیں",
          "Already Registered?": "پہلے سے رجسٹرڈ ہے؟",
          "Pick Image": "تصویر چنیں",
          "Product Name": "پروڈکٹ کا نام",
          "Product Description": "مصنوعات کی تفصیل",
          "Phone Number": "فون نمبر",
          "Second Phone Number": "دوسرا فون نمبر",
          "Product Price": "مصنوعات کی قیمت",
          "Pick Location": "مقام کا انتخاب کریں",
          "Record Voice": "آواز ریکارڈ کریں",
          "Update Profile": "پروفائل کو اپ ڈیٹ کریں",
          "Send Feedback": "رائے بھیجیں",
          "View Reply": "جواب دیکھیں",
          "Log out": "لاگ آؤٹ",
          "Submit": "جمع کریں",
          "Mark as Sold": "بیچ کے طور پر نشان زد کریں",
          "Delete": "ڈیلیٹ",
          "Post New": "نئی پوسٹ کریں",
          "Sell": "بیچ",
          "Rates": "ریٹ",
          "Profile": "پروفائل",
          "Plastic": "پلاسٹک",
          'Select Scrap Type': 'اسکریپ کی قسم منتخب کریں',
          'Edit Profile': 'پروفائل میں ترمیم کریں',
          'Edit and update your profile information':
              'اپنی پروفائل کی معلومات میں ترمیم اور اپ ڈیٹ کریں',
          'Send Feedback to admin': 'ایڈمن کو تاثرات بھیجیں',
          'Share your feedback with us': 'اپنی رائے ہمارے ساتھ شیئر کریں',
          'View admin Reply': 'ایڈمن کا جواب دیکھیں',
          'Check replies to your feedback': 'اپنے تاثرات کے جوابات چیک کریں',
          'Logout': 'لاگ آؤٹ',
          'Sign out of your account': 'اپنے اکاؤنٹ سے سائن آؤٹ کریں',
          "Second Phone Number (Optional)": "دوسرا فون نمبر (اختیاری)",
          "Home": "گھر",
          "Profile": "پروفائل",
          "Bids": "بولیاں",
          "VIew All Bids": "تمام بولیاں دیکھیں",
          "Post Bid": "پوسٹ بولی",
          "Approved": "منظور شدہ",
          "Pending": "زیر التواء",
          "Send Bid": "بولی بھیجیں",
          'Metal': 'لوہا',
          'Wood': 'لکڑی',
          'Paper': 'کاغذ',
          'Fabric': 'فیبرک',
          'Machinery': 'مشینری',
          "Search": 'تلاش',
          "Product Details": "پروڈکٹ کی تفصیلات",
          "Track Location": "ٹریک لوکیشن",
          "Call Number One": "ایک نمبر پر کال کریں",
          "Call Number Two": "دو نمبر پر کال کریں",
          "Clear All": "سب صاف کریں",
          "Apply": "درخواست دیں",
          'Features:': 'خصوصیات:',
          "Select Filters": "فلٹرز منتخب کریں"
        },
      };
}
